FROM alpine:3

LABEL author="Muhammad Sabran"
LABEL company="Mencari Cinta Sejati" website="https://www.gacorbang88.com"

RUN mkdir praktikum
RUN echo "Gwaenchanayo pheii" > "praktikum/gwenchana.txt"

CMD cat "praktikum/gwenchana.txt"

